In [31]:
import numpy as np
array = np.array([1,2],dtype=int)
print(array)

[1 2]


In [ ]:
import array as ar
array = ar.array('i',[1,2,3,4,5])
print(array)
#time and space complexity is O(n)

array('i', [1, 2, 3, 4, 5])


In [ ]:
print(array[0])

1


In [12]:
import numpy as np
array = np.array([[1,2,3,4],[7,9,11,19]])
print(array)
array2= np.insert(array, 1, [[9,10,11,13]],axis=0) # axis-0 is for row , and 1 is for column
print(array2)
array3= np.insert(array2, 2, [[9,10,11]],axis=1) # axis-0 is for row , and 1 is for column
print(array3)

[[ 1  2  3  4]
 [ 7  9 11 19]]
[[ 1  2  3  4]
 [ 9 10 11 13]
 [ 7  9 11 19]]
[[ 1  2  9  3  4]
 [ 9 10 10 11 13]
 [ 7  9 11 11 19]]


In [19]:
def accesing_array(array, rowindex, colindex):
  if rowindex >= len(array) or colindex >= len(array[0]):
    print("row or col index is not valid")
  else:
    print(array[rowindex][colindex])
accesing_array(array3, 2, 1)

9


In [20]:
def traversal(array):
  row_index = len(array)
  col_index = len(array[0])
  for i in range(row_index):
    for j in range(col_index):
      print(array[i][j])
traversal(array3)

1
2
9
3
4
9
10
10
11
13
7
9
11
11
19


In [24]:
def search(array, element):
  row_index = len(array)
  col_index = len(array[0])
  for i in range(row_index):
    for j in range(col_index):
      if array[i][j] == element:
        print(f'found at index at {i}{j}')
search(array3, 4)

found at index at 04


In [26]:
import numpy as np
array4 = np.delete(array3, 1, axis=1)
print(array4)

[[ 1  9  3  4]
 [ 9 10 11 13]
 [ 7 11 11 19]]
